# -*- coding: utf-8 -*-
"""iml1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115H0F73vTjTm6138pOoGZwEz8r3R_JWa
"""

from google.colab import files


uploaded = files.upload()

import numpy as np
import pandas as pd
data=pd.read_csv('text.csv')
data.head()

concepts = np.array(data)[:,:-1]
concepts

target = np.array(data)[:,-1]
target

def train(con,tar):
    for i,val in enumerate(tar):
        if val=='yes':
            specific_h =  con[i].copy()
            break
    for i,val in enumerate(con):
        if tar[i]=='yes':
            for x in range(len(specific_h)):
                if val[x] != specific_h[x]:
                    specific_h[x] = '?'
                else:
                    pass
    return specific_h

print(train(concepts,target))